/**
  ******************************************************************************
  * @file     bootloader.c
  * @author   Auto-generated by STM32CubeIDE, Alexey Polurotov
  * @version  V1.0
  * @date     12/03/2025
  * @brief    Bootloader library.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx_hal.h"
#include "bootloader.h"

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
}

inline void bootloader_jump_to_user_app(uint32_t app_address)
{
	typedef void (*pFunction)(void);

	SysTick->CTRL = 0x0;
	SysTick->LOAD = 0x0;
	SysTick->VAL  = 0x0;
	HAL_DeInit();
	RCC->CIR = 0x00000000;

	// fn_ptr to hold the address of the user_application's reset_handler
	pFunction fn_ptr_void_void = NULL;
	// configure MSP by reading the first word of the user_application region in Flash memory
	uint32_t msp_value = *( (volatile uint32_t *) app_address );
//	printmsg("[BL_DBG]: MSP value = 0x%x\n", msp_value);
	__set_MSP(msp_value); //CMSIS API
	__DMB();
	__disable_irq();
	SCB->VTOR = app_address;
	__DSB();
	__enable_irq();
	__ISB();

	// store the addr of user_application's reset_handler in the fn_ptr
	const uint32_t reset_handler_addr = *( (const volatile uint32_t *) (app_address + 4U) );
//	printmsg("[BL_DBG]: reset_handler_addr of user_application = 0x%x\n", reset_handler_addr);
	fn_ptr_void_void = (void *) reset_handler_addr;

	// jump to the reset_handler of user_application
//	printmsg("[BL_DBG]: bootloader jumping to user_application...\n");
	fn_ptr_void_void();
} // void bootloader_jump_to_user_app(uint32_t app_address)
