/**
  ******************************************************************************
  * @file     memory.c
  * @author   Auto-generated by STM32CubeIDE, Alexey Polurotov
  * @version  V1.0
  * @date     27/02/2025
  * @brief    Memory management.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include <flash_memory.h>
#include <string.h>

#include "stm32f4xx_hal.h"

// external flash
#if 0
uint8_t buffer[256];
bool flash_is_empty;
#endif

// ---------------------------------------------------------------------------------------------------
// internal flash
// this is variable structure saved in RAM for ability of data changing
stored_data_u stored_data;

/**
  * @bref	read flash
  * @param	flash_s
  * @retval	flash_s
  */
flash_s flash_read_imp(flash_s in)
{
	flash_s out = in;
	uint32_t FlashMemAddress = FLASH_SECTOR5_BASE_ADDRESS;
	uint32_t tempAddrs = FlashMemAddress;

#if 0
	memset(out.rd32, 0, sizeof(out.rd32));
	for (size_t i = 0; i < out.len; ++i)
	{
		out.rd32[i] = *(__IO uint32_t*) tempAddrs;
	    tempAddrs += 4;
	}
#else
	memset(out.data, 0, sizeof(out.data));
	for (size_t i = 0; i < out.count; ++i)
	{
		out.data[i] = *(__IO uint8_t*) tempAddrs;
	    tempAddrs += 1;
	}
#endif

	return out;
}

/**
  * @bref	write flash
  * @param	flash_s
  * @retval	flash_s
  */
flash_s flash_write_imp(flash_s in)
{
	flash_s out = in;
	__disable_irq(); // отключаем прерывания, чтобы не нарушать процесс записи
	out.status = HAL_FLASH_Unlock();
	if (out.status != HAL_OK)
	{
		goto end;
	}

	uint32_t FlashMemAddress = FLASH_SECTOR5_BASE_ADDRESS;

	for (size_t i = 0; i < in.count; ++i)
	{
		out.status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE, FlashMemAddress, in.data[i]);
		if (out.status != HAL_OK)
		{
			HAL_FLASH_Lock();
			goto end;
		}
		FlashMemAddress += 1;
	}

	out.status = HAL_FLASH_Lock();
end:
	__enable_irq();
	return out;
}

/**
  * @bref	erase flash
  * @param	flash_s
  * @retval	flash_s
  */
flash_s flash_erase_imp(flash_s in)
{
	flash_s out = in;
	__disable_irq(); // отключаем прерывания, чтобы не нарушать процесс записи
	out.status = HAL_FLASH_Unlock();
	if (out.status != HAL_OK)
	{
		goto end;
	}

	FLASH_EraseInitTypeDef FlashErase = {
			.Sector = FLASH_SECTOR_5,
			.NbSectors = 1,
			.TypeErase = FLASH_TYPEERASE_SECTORS,
			.VoltageRange = (int8_t)VOLTAGE_RANGE_3,
	};
	uint32_t SectorError = 0;

	out.status = HAL_FLASHEx_Erase(&FlashErase, &SectorError);
	if (out.status != HAL_OK)
	{
		HAL_FLASH_Lock();
		goto end;
	}

	out.status = HAL_FLASH_Lock();
end:
	__enable_irq();
	return out;
}

// ---------------------------------------------------------------------------------------------------
// external flash by SPI
#if 0
uint16_t Read_ID(void)
{
	uint8_t temp[4] = {0,};
	W25_CSL;
	temp[0] = ID_READ;
	HAL_SPI_Transmit(&hspi1, temp, 4, 1);
	while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY)
	{
		__NOP();
	}
	HAL_SPI_Receive(&hspi1, temp, 2, 1);
	W25_CSH;
	return ((temp[0]<<8) | temp[1]);
}

uint32_t Read_JEDEC(void)
{
	uint8_t temp[4] = {0,};
	W25_CSL;
	temp[0] = JEDEC_READ;
	HAL_SPI_Transmit(&hspi1, temp, 1, 1);
	while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY)
	{
		__NOP();
	}
	HAL_SPI_Receive(&hspi1, temp, 3, 1);
	W25_CSH;
	return ((temp[0]<<16) | (temp[1]<<8) | temp[2]);
}

uint8_t Read_SR1(void)
{
	uint8_t temp[1];
	W25_CSL;
	temp[0] = SR1_READ;
	HAL_SPI_Transmit(&hspi1, temp, 1, 1);
	while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY)
	{
		__NOP();
	}
	HAL_SPI_Receive(&hspi1, temp, 1, 1);
	W25_CSH;
	return temp[0];
}

void Read_Page(uint32_t addr, uint8_t *rData)
{
	uint8_t temp[4] = {0,};
	while (Read_SR1() & 1)
	{
		__NOP();
	}
	W25_CSL;
	temp[0] = READ;
	temp[1] = (addr>>16) & 0xff;
	temp[2] = (addr>>8) & 0xff;
	temp[3] = addr & 0xff;
	HAL_SPI_Transmit(&hspi1, temp, 4, 1);
	while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY)
	{
		__NOP();
	}
	HAL_SPI_Receive(&hspi1, rData, 256, 1);
	W25_CSH;
}

void WriteEnable(void)
{
	uint8_t temp[1];
	W25_CSL;
	temp[0] = WRITE_EN;
	HAL_SPI_Transmit(&hspi1, temp, 1, 1);
	W25_CSH;
}

void WriteDisable(void)
{
	uint8_t temp[1];
	W25_CSL;
	temp[0] = WRITE_DS;
	HAL_SPI_Transmit(&hspi1, temp, 1, 1);
	W25_CSH;
}

void Write_Page(uint32_t addr, uint8_t *wData)
{
	uint8_t temp[4] = {0,};
	while (Read_SR1() & 1)
	{
		__NOP();
	}
	W25_CSL;
	temp[0] = WRITE;
	temp[1] = (addr>>16) &  0xff;
	temp[2] = (addr>>8) & 0xff;
	temp[3] = addr & 0xff;
	HAL_SPI_Transmit(&hspi1, temp, 4, 1);
	HAL_SPI_Transmit(&hspi1, wData, 256, 1);
	while (HAL_SPI_GetState(&hspi1) != HAL_SPI_STATE_READY)
	{
		__NOP();
	}
	W25_CSH;
}

void EraseSec(uint32_t addr)
{
	uint8_t temp[4] = {0,};
	while (Read_SR1() & 1)
	{
		__NOP();
	}
	W25_CSL;
	temp[0] = ERASE_SEC;
	temp[1] = (addr>>16) & 0xff;
	temp[2] = (addr>>8) & 0xff;
	temp[3] = addr & 0xff;
	HAL_SPI_Transmit(&hspi1, temp, 4, 1);
	W25_CSH;
	HAL_Delay(1);
}

// using
void loop()
{
	if (!HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_3))
	{
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET);
		Read_Page(0, buffer);
		sprintf(str_tx,
				"ID: %x\r\n" \
				"JEDEC: %lx\r\n" \
				"%02x %02x %02x %02x %02x %02x %02x %02x %02x\r\n",
				Read_ID(), Read_JEDEC(),
				buffer[0], buffer[1], buffer[2], buffer[3], buffer[4], buffer[5], buffer[6], buffer[7], buffer[8]);
		CDC_Transmit_FS((unsigned char*)str_tx, strlen(str_tx));
		HAL_Delay(500);
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET);
		goto end;
	}
	else if (!HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_4))
	{
		HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET);
		if (flash_is_empty)
		{
			WriteEnable();
			for (uint16_t i = 0; i < 256; ++i)
			{
				buffer[i] = 0xff;
			}
			buffer[0] = 0x55;
			buffer[1] = 0xff;
			buffer[2] = 0x00;
			buffer[3] = 0xAA;
			Write_Page(0, buffer);
			WriteDisable();
			flash_is_empty = false;
			sprintf(str_tx, "Flash has modified!\r\n");
			CDC_Transmit_FS((unsigned char*)str_tx, strlen(str_tx));
			HAL_Delay(500);
			HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET);
			goto end;
		}
		else if (buffer[0] != 0xff)
		{
			WriteEnable();
			EraseSec(0);
			WriteDisable();
			flash_is_empty = true;
			sprintf(str_tx, "Flash has erased!\r\n");
			CDC_Transmit_FS((unsigned char*)str_tx, strlen(str_tx));
			HAL_Delay(500);
			HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET);
		}
		goto end;
	}
	HAL_Delay(500);

	end:
		__NOP();
	return;
}

#endif
