/*******************************************************************************
* Filename      : syscfgvrefbufregisters.hpp
*
* Details       : SYSCFG_VREFBUF. This header file is auto-generated for
*                 STM32WB55_CM4 device.
*
*
*******************************************************************************/

#pragma once

#include "syscfgvrefbuffieldvalues.hpp"  //for Bits Fields defs 
#include "registerbase.hpp"   //for RegisterBase
#include "register.hpp"       //for Register
#include "accessmode.hpp"     //for ReadMode, WriteMode, ReadWriteMode  

struct SYSCFG_VREFBUF
{
  struct SYSCFG_VREFBUFSYSCFG_MEMRMPBase {} ;

  struct SYSCFG_MEMRMP : public RegisterBase<0x40010000, 32, ReadWriteMode>
  {
    using MEM_MODE = SYSCFG_VREFBUF_SYSCFG_MEMRMP_MEM_MODE_Values<SYSCFG_VREFBUF::SYSCFG_MEMRMP, 0, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_MEMRMPBase> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_MEMRMP_MEM_MODE_Values<SYSCFG_VREFBUF::SYSCFG_MEMRMP, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_MEMRMPPack  = Register<0x40010000, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_MEMRMPBase, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_CFGR1Base {} ;

  struct SYSCFG_CFGR1 : public RegisterBase<0x40010004, 32, ReadWriteMode>
  {
    using FPU_IE = SYSCFG_VREFBUF_SYSCFG_CFGR1_FPU_IE_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 26, 6, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C3_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C3_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 22, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C1_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C1_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 20, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C_PB9_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C_PB9_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 19, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C_PB8_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C_PB8_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 18, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C_PB7_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C_PB7_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 17, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using I2C_PB6_FMP = SYSCFG_VREFBUF_SYSCFG_CFGR1_I2C_PB6_FMP_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 16, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using BOOSTEN = SYSCFG_VREFBUF_SYSCFG_CFGR1_BOOSTEN_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 8, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_CFGR1_BOOSTEN_Values<SYSCFG_VREFBUF::SYSCFG_CFGR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_CFGR1Pack  = Register<0x40010004, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR1Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_EXTICR1Base {} ;

  struct SYSCFG_EXTICR1 : public RegisterBase<0x40010008, 32, ReadWriteMode>
  {
    using EXTI3 = SYSCFG_VREFBUF_SYSCFG_EXTICR1_EXTI3_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR1, 12, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR1Base> ;
    using EXTI2 = SYSCFG_VREFBUF_SYSCFG_EXTICR1_EXTI2_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR1, 8, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR1Base> ;
    using EXTI1 = SYSCFG_VREFBUF_SYSCFG_EXTICR1_EXTI1_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR1, 4, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR1Base> ;
    using EXTI0 = SYSCFG_VREFBUF_SYSCFG_EXTICR1_EXTI0_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR1, 0, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR1Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_EXTICR1_EXTI0_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR1Pack  = Register<0x40010008, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR1Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_EXTICR2Base {} ;

  struct SYSCFG_EXTICR2 : public RegisterBase<0x4001000C, 32, ReadWriteMode>
  {
    using EXTI7 = SYSCFG_VREFBUF_SYSCFG_EXTICR2_EXTI7_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR2, 12, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR2Base> ;
    using EXTI6 = SYSCFG_VREFBUF_SYSCFG_EXTICR2_EXTI6_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR2, 8, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR2Base> ;
    using EXTI5 = SYSCFG_VREFBUF_SYSCFG_EXTICR2_EXTI5_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR2, 4, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR2Base> ;
    using EXTI4 = SYSCFG_VREFBUF_SYSCFG_EXTICR2_EXTI4_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR2, 0, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR2Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_EXTICR2_EXTI4_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR2Pack  = Register<0x4001000C, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR2Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_EXTICR3Base {} ;

  struct SYSCFG_EXTICR3 : public RegisterBase<0x40010010, 32, ReadWriteMode>
  {
    using EXTI11 = SYSCFG_VREFBUF_SYSCFG_EXTICR3_EXTI11_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR3, 12, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR3Base> ;
    using EXTI10 = SYSCFG_VREFBUF_SYSCFG_EXTICR3_EXTI10_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR3, 8, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR3Base> ;
    using EXTI9 = SYSCFG_VREFBUF_SYSCFG_EXTICR3_EXTI9_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR3, 4, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR3Base> ;
    using EXTI8 = SYSCFG_VREFBUF_SYSCFG_EXTICR3_EXTI8_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR3, 0, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR3Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_EXTICR3_EXTI8_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR3, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR3Pack  = Register<0x40010010, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR3Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_EXTICR4Base {} ;

  struct SYSCFG_EXTICR4 : public RegisterBase<0x40010014, 32, ReadWriteMode>
  {
    using EXTI15 = SYSCFG_VREFBUF_SYSCFG_EXTICR4_EXTI15_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR4, 12, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR4Base> ;
    using EXTI14 = SYSCFG_VREFBUF_SYSCFG_EXTICR4_EXTI14_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR4, 8, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR4Base> ;
    using EXTI13 = SYSCFG_VREFBUF_SYSCFG_EXTICR4_EXTI13_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR4, 4, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR4Base> ;
    using EXTI12 = SYSCFG_VREFBUF_SYSCFG_EXTICR4_EXTI12_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR4, 0, 3, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR4Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_EXTICR4_EXTI12_Values<SYSCFG_VREFBUF::SYSCFG_EXTICR4, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_EXTICR4Pack  = Register<0x40010014, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_EXTICR4Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_SCSRBase {} ;

  struct SYSCFG_SCSR : public RegisterBase<0x40010018, 32, ReadWriteMode>
  {
    using SRAM2BSY = SYSCFG_VREFBUF_SYSCFG_SCSR_SRAM2BSY_Values<SYSCFG_VREFBUF::SYSCFG_SCSR, 1, 1, ReadMode, SYSCFG_VREFBUFSYSCFG_SCSRBase> ;
    using SRAM2ER = SYSCFG_VREFBUF_SYSCFG_SCSR_SRAM2ER_Values<SYSCFG_VREFBUF::SYSCFG_SCSR, 0, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SCSRBase> ;
    using C2RFD = SYSCFG_VREFBUF_SYSCFG_SCSR_C2RFD_Values<SYSCFG_VREFBUF::SYSCFG_SCSR, 31, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SCSRBase> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_SCSR_C2RFD_Values<SYSCFG_VREFBUF::SYSCFG_SCSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_SCSRPack  = Register<0x40010018, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SCSRBase, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_CFGR2Base {} ;

  struct SYSCFG_CFGR2 : public RegisterBase<0x4001001C, 32, ReadWriteMode>
  {
    using SPF = SYSCFG_VREFBUF_SYSCFG_CFGR2_SPF_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 8, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base> ;
    using ECCL = SYSCFG_VREFBUF_SYSCFG_CFGR2_ECCL_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 3, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base> ;
    using PVDL = SYSCFG_VREFBUF_SYSCFG_CFGR2_PVDL_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 2, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base> ;
    using SPL = SYSCFG_VREFBUF_SYSCFG_CFGR2_SPL_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 1, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base> ;
    using CLL = SYSCFG_VREFBUF_SYSCFG_CFGR2_CLL_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 0, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_CFGR2_CLL_Values<SYSCFG_VREFBUF::SYSCFG_CFGR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_CFGR2Pack  = Register<0x4001001C, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_CFGR2Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_SWPRBase {} ;

  struct SYSCFG_SWPR : public RegisterBase<0x40010020, 32, WriteMode>
  {
    using P31WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P31WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 31, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P30WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P30WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 30, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P29WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P29WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 29, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P28WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P28WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 28, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P27WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P27WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 27, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P26WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P26WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 26, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P25WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P25WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 25, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P24WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P24WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 24, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P23WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P23WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 23, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P22WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P22WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 22, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P21WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P21WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 21, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P20WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P20WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 20, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P19WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P19WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 19, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P18WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P18WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 18, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P17WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P17WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 17, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P16WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P16WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 16, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P15WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P15WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 15, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P14WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P14WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 14, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P13WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P13WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 13, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P12WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P12WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 12, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P11WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P11WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 11, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P10WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P10WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 10, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P9WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P9WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 9, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P8WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P8WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 8, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P7WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P7WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 7, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P6WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P6WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 6, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P5WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P5WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 5, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P4WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P4WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 4, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P3WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P3WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 3, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P2WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P2WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 2, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P1WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P1WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 1, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using P0WP = SYSCFG_VREFBUF_SYSCFG_SWPR_P0WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 0, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_SWPR_P0WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_SWPRPack  = Register<0x40010020, 32, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPRBase, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_SKRBase {} ;

  struct SYSCFG_SKR : public RegisterBase<0x40010024, 32, WriteMode>
  {
    using KEY = SYSCFG_VREFBUF_SYSCFG_SKR_KEY_Values<SYSCFG_VREFBUF::SYSCFG_SKR, 0, 8, WriteMode, SYSCFG_VREFBUFSYSCFG_SKRBase> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_SKR_KEY_Values<SYSCFG_VREFBUF::SYSCFG_SKR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_SKRPack  = Register<0x40010024, 32, WriteMode, SYSCFG_VREFBUFSYSCFG_SKRBase, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_SWPR2Base {} ;

  struct SYSCFG_SWPR2 : public RegisterBase<0x40010028, 32, WriteMode>
  {
    using P63WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P63WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 31, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P62WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P62WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 30, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P61WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P61WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 29, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P60WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P60WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 28, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P59WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P59WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 27, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P58WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P58WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 26, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P57WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P57WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 25, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P56WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P56WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 24, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P55WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P55WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 23, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P54WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P54WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 22, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P53WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P53WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 21, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P52WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P52WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 20, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P51WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P51WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 19, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P50WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P50WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 18, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P49WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P49WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 17, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P48WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P48WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 16, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P47WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P47WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 15, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P46WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P46WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 14, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P45WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P45WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 13, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P44WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P44WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 12, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P43WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P43WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 11, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P42WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P42WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 10, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P41WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P41WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 9, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P40WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P40WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 8, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P39WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P39WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 7, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P38WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P38WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 6, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P37WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P37WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 5, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P36WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P36WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 4, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P35WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P35WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 3, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P34WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P34WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 2, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P33WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P33WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 1, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using P32WP = SYSCFG_VREFBUF_SYSCFG_SWPR2_P32WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 0, 1, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_SWPR2_P32WP_Values<SYSCFG_VREFBUF::SYSCFG_SWPR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_SWPR2Pack  = Register<0x40010028, 32, WriteMode, SYSCFG_VREFBUFSYSCFG_SWPR2Base, T...> ;

  struct SYSCFG_VREFBUFVREFBUF_CSRBase {} ;

  struct VREFBUF_CSR : public RegisterBase<0x40010030, 32, ReadWriteMode>
  {
    using ENVR = SYSCFG_VREFBUF_VREFBUF_CSR_ENVR_Values<SYSCFG_VREFBUF::VREFBUF_CSR, 0, 1, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CSRBase> ;
    using HIZ = SYSCFG_VREFBUF_VREFBUF_CSR_HIZ_Values<SYSCFG_VREFBUF::VREFBUF_CSR, 1, 1, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CSRBase> ;
    using VRS = SYSCFG_VREFBUF_VREFBUF_CSR_VRS_Values<SYSCFG_VREFBUF::VREFBUF_CSR, 2, 1, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CSRBase> ;
    using VRR = SYSCFG_VREFBUF_VREFBUF_CSR_VRR_Values<SYSCFG_VREFBUF::VREFBUF_CSR, 3, 1, ReadMode, SYSCFG_VREFBUFVREFBUF_CSRBase> ;
    using FieldValues = SYSCFG_VREFBUF_VREFBUF_CSR_VRR_Values<SYSCFG_VREFBUF::VREFBUF_CSR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using VREFBUF_CSRPack  = Register<0x40010030, 32, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CSRBase, T...> ;

  struct SYSCFG_VREFBUFVREFBUF_CCRBase {} ;

  struct VREFBUF_CCR : public RegisterBase<0x40010034, 32, ReadWriteMode>
  {
    using TRIM = SYSCFG_VREFBUF_VREFBUF_CCR_TRIM_Values<SYSCFG_VREFBUF::VREFBUF_CCR, 0, 6, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CCRBase> ;
    using FieldValues = SYSCFG_VREFBUF_VREFBUF_CCR_TRIM_Values<SYSCFG_VREFBUF::VREFBUF_CCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using VREFBUF_CCRPack  = Register<0x40010034, 32, ReadWriteMode, SYSCFG_VREFBUFVREFBUF_CCRBase, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_IMR1Base {} ;

  struct SYSCFG_IMR1 : public RegisterBase<0x40010100, 32, ReadWriteMode>
  {
    using TIM1IM = SYSCFG_VREFBUF_SYSCFG_IMR1_TIM1IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 13, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using TIM16IM = SYSCFG_VREFBUF_SYSCFG_IMR1_TIM16IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 14, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using TIM17IM = SYSCFG_VREFBUF_SYSCFG_IMR1_TIM17IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 15, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT5IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT5IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 21, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT6IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT6IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 22, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT7IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT7IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 23, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT8IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT8IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 24, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT9IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT9IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 25, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT10IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT10IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 26, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT11IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT11IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 27, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT12IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT12IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 28, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT13IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT13IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 29, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT14IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT14IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 30, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using EXIT15IM = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT15IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 31, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_IMR1_EXIT15IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_IMR1Pack  = Register<0x40010100, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR1Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_IMR2Base {} ;

  struct SYSCFG_IMR2 : public RegisterBase<0x40010104, 32, ReadWriteMode>
  {
    using PVM3IM = SYSCFG_VREFBUF_SYSCFG_IMR2_PVM3IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR2, 18, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR2Base> ;
    using PVM1IM = SYSCFG_VREFBUF_SYSCFG_IMR2_PVM1IM_Values<SYSCFG_VREFBUF::SYSCFG_IMR2, 16, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR2Base> ;
    using PVDIM = SYSCFG_VREFBUF_SYSCFG_IMR2_PVDIM_Values<SYSCFG_VREFBUF::SYSCFG_IMR2, 20, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR2Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_IMR2_PVDIM_Values<SYSCFG_VREFBUF::SYSCFG_IMR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_IMR2Pack  = Register<0x40010104, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_IMR2Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_C2IMR1Base {} ;

  struct SYSCFG_C2IMR1 : public RegisterBase<0x40010108, 32, ReadWriteMode>
  {
    using RTCSTAMP = SYSCFG_VREFBUF_SYSCFG_C2IMR1_RTCSTAMP_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 0, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using RTCWKUP = SYSCFG_VREFBUF_SYSCFG_C2IMR1_RTCWKUP_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 3, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using RTCALARM = SYSCFG_VREFBUF_SYSCFG_C2IMR1_RTCALARM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 4, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using RCC = SYSCFG_VREFBUF_SYSCFG_C2IMR1_RCC_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 5, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using FLASH = SYSCFG_VREFBUF_SYSCFG_C2IMR1_FLASH_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 6, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using PKA = SYSCFG_VREFBUF_SYSCFG_C2IMR1_PKA_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 8, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using RNG = SYSCFG_VREFBUF_SYSCFG_C2IMR1_RNG_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 9, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using AES1 = SYSCFG_VREFBUF_SYSCFG_C2IMR1_AES1_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 10, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using COMP = SYSCFG_VREFBUF_SYSCFG_C2IMR1_COMP_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 11, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using ADC = SYSCFG_VREFBUF_SYSCFG_C2IMR1_ADC_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 12, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_C2IMR1_ADC_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR1, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_C2IMR1Pack  = Register<0x40010108, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR1Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_C2IMR2Base {} ;

  struct SYSCFG_C2IMR2 : public RegisterBase<0x4001010C, 32, ReadWriteMode>
  {
    using DMA1_CH1_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH1_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 0, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH2_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH2_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 1, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH3_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH3_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 2, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH4_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH4_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 3, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH5_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH5_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 4, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH6_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH6_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 5, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA1_CH7_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA1_CH7_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 6, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH1_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH1_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 8, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH2_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH2_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 9, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH3_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH3_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 10, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH4_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH4_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 11, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH5_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH5_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 12, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH6_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH6_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 13, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMA2_CH7_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMA2_CH7_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 14, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using DMAM_UX1_IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_DMAM_UX1_IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 15, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using PVM1IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_PVM1IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 16, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using PVM3IM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_PVM3IM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 18, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using PVDIM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_PVDIM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 20, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using TSCIM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_TSCIM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 21, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using LCDIM = SYSCFG_VREFBUF_SYSCFG_C2IMR2_LCDIM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 22, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_C2IMR2_LCDIM_Values<SYSCFG_VREFBUF::SYSCFG_C2IMR2, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_C2IMR2Pack  = Register<0x4001010C, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_C2IMR2Base, T...> ;

  struct SYSCFG_VREFBUFSYSCFG_SIPCRBase {} ;

  struct SYSCFG_SIPCR : public RegisterBase<0x40010110, 32, ReadWriteMode>
  {
    using SAES1 = SYSCFG_VREFBUF_SYSCFG_SIPCR_SAES1_Values<SYSCFG_VREFBUF::SYSCFG_SIPCR, 0, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SIPCRBase> ;
    using SAES2 = SYSCFG_VREFBUF_SYSCFG_SIPCR_SAES2_Values<SYSCFG_VREFBUF::SYSCFG_SIPCR, 1, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SIPCRBase> ;
    using SPKA = SYSCFG_VREFBUF_SYSCFG_SIPCR_SPKA_Values<SYSCFG_VREFBUF::SYSCFG_SIPCR, 2, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SIPCRBase> ;
    using SRNG = SYSCFG_VREFBUF_SYSCFG_SIPCR_SRNG_Values<SYSCFG_VREFBUF::SYSCFG_SIPCR, 3, 1, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SIPCRBase> ;
    using FieldValues = SYSCFG_VREFBUF_SYSCFG_SIPCR_SRNG_Values<SYSCFG_VREFBUF::SYSCFG_SIPCR, 0, 0, NoAccess, NoAccess> ;
  } ;

  template<typename... T> 
  using SYSCFG_SIPCRPack  = Register<0x40010110, 32, ReadWriteMode, SYSCFG_VREFBUFSYSCFG_SIPCRBase, T...> ;

} ;

