/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32WB55_CM4/rccregisters.hpp"
#include "STM32WB55_CM4/gpiobregisters.hpp"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC::AHB2ENR::GPIOBEN::Enable::Set();
	GPIOB::MODER::MODER5::Output::Set();
	GPIOB::OSPEEDR::OSPEEDR5::FastSpeed::Set();
	GPIOB::MODER::MODER0::Output::Set();
	GPIOB::MODER::MODER1::Output::Set();

    /* Loop forever */
	for(;;)
	{
		GPIOB::BSRR::BS5::High::Write();
		GPIOB::BSRR::BS0::High::Write();
		GPIOB::BSRR::BS1::High::Write();
		for (int i = 0; i < 100000; ++i)
		{
		}
		GPIOB::BSRR::BR5::Low::Write();
		GPIOB::BSRR::BR0::Low::Write();
		GPIOB::BSRR::BR1::Low::Write();
		for (int i = 0; i < 100000; ++i)
		{
		}
	}
}
