/**
  ******************************************************************************
  * @file     nvram.c
  * @author   Auto-generated by STM32CubeIDE, Alexey Polurotov
  * @version  V1.0
  * @date     27/02/2025
  * @brief    NVRAM library for STM32F1XX with HAL-Driver
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include <stdbool.h>
#include "nvram.h"

/** Functions ----------------------------------------------------------------*/
void myFunction(void)
{
}

// private function prototypes
static NVRAM_Result_e NVRAM_PageTransfer();
static NVRAM_Result_e NVRAM_SetPageStatus(NVRAM_Page_e Page, NVRAM_PageStatus_e PageStatus);
static NVRAM_Result_e NVRAM_PageToIndex(NVRAM_Page_e Page);

// global variables
static uint8_t  NVRAM_SizeTable[NVRAM_VARIABLE_COUNT];		// NVRAM_SizeTable[i]: actual size of variable i (as NVRAM_Size_e)
static uint16_t NVRAM_Index[NVRAM_VARIABLE_COUNT];			// NVRAM_Index[i]: actual address of variable i (physical address = NVRAM_START_ADDRESS + NVRAM_Index[i])

static uint32_t NVRAM_ValidPage     = NVRAM_PAGE_NONE;
static uint32_t NVRAM_ReceivingPage = NVRAM_PAGE_NONE;
static uint32_t NVRAM_ErasedPage    = NVRAM_PAGE_NONE;

static uint32_t NVRAM_NextIndex = 0;

// initialize the NVRAM & restore the pages to a known good state in case of page's status corruption after a power loss
// - unlock flash
// - read each page status and check if valid
// - if invalid page status, format EEPROM
// - set global variables ValidPage, ReceivingPage and ErasedPage
// - build address index
// - resume page transfer if needed
//
// return: NVRAM_SUCCESS, NVRAM_NO_VALID_PAGE, NVRAM_FULL, NVRAM_ERROR, NVRAM_BUSY, NVRAM_TIMEOUT
NVRAM_Result_e NVRAM_Init()
{
	NVRAM_Result_e result;

	HAL_FLASH_Unlock();

	// read each page status and check if valid
	NVRAM_PageStatus_e PageStatus0 = *((__IO uint16_t*) NVRAM_PAGE0);
	NVRAM_PageStatus_e PageStatus1 = *((__IO uint16_t*) NVRAM_PAGE1);
//	uint8_t InvalidState = 0;
	bool InvalidState = false;
	if (PageStatus0 != NVRAM_VALID && PageStatus0 != NVRAM_RECEIVING && PageStatus0 != NVRAM_ERASED)
	{
		InvalidState = true;
	}
	if (PageStatus1 != NVRAM_VALID && PageStatus1 != NVRAM_RECEIVING && PageStatus1 != NVRAM_ERASED)
	{
		InvalidState = true;
	}
	if (PageStatus0 == PageStatus1)
	{
		InvalidState = true;
	}

	// if invalid page status, format NVRAM (erase both pages and set page0 as valid)
	if (InvalidState == true)
	{
//		FLASH_EraseInitTypeDef EraseDefinitions = {
//				.TypeErase   = FLASH_TYPEERASE_PAGES,
//				.Banks       = FLASH_BANK_1,
//				.PageAddress = NVRAM_PAGE0,
//				.NbPages     = 2,
//		};
		FLASH_EraseInitTypeDef EraseDefinitions = {
				.TypeErase   = FLASH_TYPEERASE_SECTORS,
				.Banks       = FLASH_BANK_1,
				.Sector      = NVRAM_PAGE0,
				.NbSectors   = 2,
		};
		uint32_t PageError;

		result = HAL_FLASHEx_Erase(&EraseDefinitions, &PageError); // TODO: HAL_FLASHEx_Erase returns HAL_StatusTypeDef not the NVRAM_Result_e
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}

		result = HAL_FLASH_Program(NVRAM_SIZE16, NVRAM_PAGE0, NVRAM_VALID); // TODO: HAL_FLASH_Program returns HAL_StatusTypeDef not the NVRAM_Result_e
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}

		PageStatus0 = NVRAM_VALID;
		PageStatus1 = NVRAM_ERASED;
	}

	// set global variables ValidPage, ReceivingPage and ErasedPage (one stays NVRAM_PAGE_NONE)
	if (PageStatus0 == NVRAM_VALID)
	{
		NVRAM_ValidPage = NVRAM_PAGE0;
	}
	if (PageStatus1 == NVRAM_VALID)
	{
		NVRAM_ValidPage = NVRAM_PAGE1;
	}
	if (PageStatus0 == NVRAM_RECEIVING)
	{
		NVRAM_ReceivingPage = NVRAM_PAGE0;
	}
	if (PageStatus1 == NVRAM_RECEIVING)
	{
		NVRAM_ReceivingPage = NVRAM_PAGE1;
	}
	if (PageStatus0 == NVRAM_ERASED)
	{
		NVRAM_ErasedPage = NVRAM_PAGE0;
	}
	if (PageStatus1 == NVRAM_ERASED)
	{
		NVRAM_ErasedPage = NVRAM_PAGE1;
	}

	// build address index (addresses from receiving page are dominant)
	NVRAM_PageToIndex(NVRAM_ValidPage);
	NVRAM_PageToIndex(NVRAM_ReceivingPage);

	// if needed, resume page transfer or just mark receiving page as valid
	if (NVRAM_ReceivingPage != NVRAM_PAGE_NONE)
	{
		if (NVRAM_ValidPage == NVRAM_PAGE_NONE)
		{
			result = NVRAM_SetPageStatus(NVRAM_ReceivingPage, NVRAM_VALID);
			if (result != NVRAM_SUCCESS)
			{
				return result;
			}
		}
		else
		{
			result = NVRAM_PageTransfer(NVRAM_ValidPage, NVRAM_ReceivingPage);
			if (result != NVRAM_SUCCESS)
			{
				return result;
			}
		}
	}

	return NVRAM_SUCCESS;
}

// returns the last stored variable value which correspond to the passed variable name
// - check if variable name exists
// - check if variable was assigned
// - read variable value from physical address with right size
//
// VariableName:	name (number) of the variable to read
// Value:			outputs the variable value
// return:			NVRAM_SUCCESS, NVRAM_INVALID_NAME, NVRAM_NOT_ASSIGNED
NVRAM_Result_e NVRAM_ReadVariable(uint16_t VariableName, NVRAM_Value_u* Value)
{
	// check if variable name exists
	if (VariableName >= NVRAM_VARIABLE_COUNT)
	{
		return NVRAM_INVALID_NAME;
	}

	// check if variable was assigned
	uint32_t Address = NVRAM_START_ADDRESS + NVRAM_Index[VariableName];
	if (Address == NVRAM_PAGE0)
	{
		return NVRAM_NOT_ASSIGNED;
	}

	// read variable value from physical address with right size
	switch (NVRAM_SizeTable[VariableName])
	{
		case NVRAM_SIZE16:
			(*Value).uInt16 = *((__IO uint16_t*) Address);
			break;
		case NVRAM_SIZE32:
			(*Value).uInt32 = *((__IO uint32_t*) Address);
			break;
		case NVRAM_SIZE64:
			(*Value).uInt64 = *((__IO uint32_t*) Address) | ((uint64_t) *((__IO uint32_t*) (Address + 4)) << 32);
			break;
		default:
			return NVRAM_NOT_ASSIGNED;
	}

	return NVRAM_SUCCESS;
}

// writes variable in NVRAM if page not full
// - get writing page's end address
// - calculate memory usage of variable
// - check if page full
//		- check if data is too much to store on one page
//		- mark the target page as receiving
//		- change next index to receiving page
//		- write the variable to target page
//		- do page transfer
// - else (if enough space)
//		- write variable value
//		- create and write variable header (size and name)
//		- update index & size table
//		- update next index
//
// VariableName:	name (number) of the variable to write
// Value:			value to be written
// Size:			size of "Value" as uint8_t. Special value NVRAM_SIZE_DELETED to mark "deleted"
// return:			NVRAM_SUCCESS, NVRAM_NO_VALID_PAGE, NVRAM_FULL, NVRAM_ERROR, NVRAM_BUSY, NVRAM_TIMEOUT
NVRAM_Result_e NVRAM_WriteVariable(uint16_t VariableName, NVRAM_Value_u Value, NVRAM_Size_e Size)
{
	NVRAM_Result_e result;

	// get writing page's end address (prefer writing to receiving page)
	NVRAM_Page_e WritingPage = NVRAM_ValidPage;
	if (NVRAM_ReceivingPage != NVRAM_PAGE_NONE)
	{
		WritingPage = NVRAM_ReceivingPage;
	}
	if (WritingPage == NVRAM_PAGE_NONE)
	{
		return NVRAM_NO_VALID_PAGE;
	}
	uint32_t PageEndAddress = WritingPage + FLASH_PAGE_SIZE;

	// calculate memory usage of variable
	uint8_t Bytes = 2 + (1 << Size);
	if (Size == NVRAM_SIZE_DELETED) Bytes = 2;

	// check if enough free space or page full
	if (NVRAM_NextIndex == 0 || PageEndAddress - NVRAM_NextIndex < Bytes)
	{
		//check if data is too much to store on one page
		uint16_t RequiredMemory = 2;
		for (uint16_t i = 0; i < NVRAM_VARIABLE_COUNT; i++)
		{
			if (i == VariableName)
			{
				RequiredMemory += 2 + (1 << Size);
			}
			else if (NVRAM_SizeTable[i] != NVRAM_SIZE_DELETED)
			{
				RequiredMemory += 2 + (1 << NVRAM_SizeTable[i]);
			}
		}
		if (RequiredMemory > FLASH_PAGE_SIZE)
		{
			return NVRAM_FULL;
		}

		// mark the empty page as receiving
		result = NVRAM_SetPageStatus(NVRAM_ErasedPage, NVRAM_RECEIVING);
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}

		// change next index to receiving page
		NVRAM_NextIndex = NVRAM_ReceivingPage + 2;

		// write the variable to receiving page (by calling this function again)
		result = NVRAM_WriteVariable(VariableName, Value, Size);
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}

		// do page transfer
		result = NVRAM_PageTransfer();
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}
	}
	// else (if enough space)
	else
	{
		// write variable value
		if (Size != NVRAM_SIZE_DELETED)
		{
			result = HAL_FLASH_Program(Size, NVRAM_NextIndex + 2, Value.uInt64); // TODO: HAL_FLASH_Program returns HAL_StatusTypeDef not the NVRAM_Result_e
			if (result != NVRAM_SUCCESS)
			{
				return result;
			}
		}

		// create and write variable header (size and name)
		uint16_t VariableHeader = VariableName + (Size << 14);
		result = HAL_FLASH_Program(FLASH_TYPEPROGRAM_HALFWORD, NVRAM_NextIndex, VariableHeader);
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}

		// update index & size table
		NVRAM_Index[VariableName] = NVRAM_NextIndex + 2 - NVRAM_START_ADDRESS;
		NVRAM_SizeTable[VariableName] = Size;
		if (Size == NVRAM_SIZE_DELETED)
		{
			NVRAM_Index[VariableName] = 0;
		}

		// update next index
		NVRAM_NextIndex += Bytes;
		if (NVRAM_NextIndex >= PageEndAddress)
		{
			NVRAM_NextIndex = 0;
		}
	}

	return NVRAM_SUCCESS;
}

// marks a variable as deleted so it can't be read anymore and is discarded on next page transfer
// - call write variable with size NVRAM_SIZE_DELETED
//
// VariableName:	name (number) of the variable to delete
// return:			NVRAM_SUCCESS, NVRAM_NO_VALID_PAGE, NVRAM_FULL, NVRAM_ERROR, NVRAM_BUSY, NVRAM_TIMEOUT
NVRAM_Result_e NVRAM_DeleteVariable(uint16_t VariableName)
{
	return NVRAM_WriteVariable(VariableName, (NVRAM_Value_u) (uint16_t) 0, NVRAM_SIZE_DELETED);
}

// transfers latest variable values from valid page to receiving page
// - get start & end address of valid page (source)
// - copy each variable
//		- check if is stored on the source page
//		- read variable value
//		- write variable to receiving page
// - erase source page
// - mark receiving page as valid
//
// return: NVRAM_SUCCESS, NVRAM_NO_VALID_PAGE, NVRAM_FULL, NVRAM_ERROR, NVRAM_BUSY, NVRAM_TIMEOUT
static NVRAM_Result_e NVRAM_PageTransfer()
{
	NVRAM_Result_e result;
	NVRAM_Value_u Value;

	// get start & end address of valid page (source) (as offset to NVRAM start)
	uint16_t StartAddress = NVRAM_ValidPage - NVRAM_START_ADDRESS;
	uint16_t EndAddress   = NVRAM_ValidPage - NVRAM_START_ADDRESS + FLASH_PAGE_SIZE;

	// copy each variable
	for (uint16_t i = 0; i < NVRAM_VARIABLE_COUNT; i++)
	{
		// check if is stored on the source page
		if (StartAddress < NVRAM_Index[i] && NVRAM_Index[i] < EndAddress)
		{
			// read variable value (if possible)
			if (NVRAM_ReadVariable(i, &Value) == NVRAM_SUCCESS)
			{
				// write variable to receiving page
				result = NVRAM_WriteVariable(i, Value, NVRAM_SizeTable[i]);
				if (result != NVRAM_SUCCESS)
				{
					return result;
				}
			}
		}
	}

	// erase source page
	result = NVRAM_SetPageStatus(NVRAM_ValidPage, NVRAM_ERASED);
	if (result != NVRAM_SUCCESS)
	{
		return result;
	}

	// mark receiving page as valid
	result = NVRAM_SetPageStatus(NVRAM_ReceivingPage, NVRAM_VALID);
	if (result != NVRAM_SUCCESS)
	{
		return result;
	}

	return NVRAM_SUCCESS;
}

// sets the page status and updates references from global variables
// - check if erase operation required
//		- remove every variable from index, that is stored on erase page
//		- setup erase definitions
//		- erase page
// - else write status to flash
// - update global page status variables
//
// Page:		page to change the status (as NVRAM_Page_e)
// PageStatus:	page status to set for page (as NVRAM_PageStatus_e)
// return:		NVRAM_SUCCESS, NVRAM_ERROR, NVRAM_BUSY or NVRAM_TIMEOUT
static NVRAM_Result_e NVRAM_SetPageStatus(NVRAM_Page_e Page, NVRAM_PageStatus_e PageStatus)
{
	NVRAM_Result_e result;

	// check if erase operation required
	if (PageStatus == NVRAM_ERASED)
	{
		// remove every variable from index, that is stored on erase page
		uint16_t StartAddress = Page - NVRAM_START_ADDRESS;
		uint16_t EndAddress = Page - NVRAM_START_ADDRESS + FLASH_PAGE_SIZE;
		for (uint16_t i = 0; i < NVRAM_VARIABLE_COUNT; i++)
		{
			if (StartAddress < NVRAM_Index[i] && NVRAM_Index[i] < EndAddress) NVRAM_Index[i] = 0;
		}

		// setup erase definitions
//		FLASH_EraseInitTypeDef EraseDefinitions = {
//				.TypeErase   = FLASH_TYPEERASE_PAGES,
//				.Banks       = FLASH_BANK_1,
//				.PageAddress = Page,
//				.NbPages     = 1
//		};
		FLASH_EraseInitTypeDef EraseDefinitions = {
				.TypeErase   = FLASH_TYPEERASE_SECTORS,
				.Banks       = FLASH_BANK_1,
				.Sector      = Page,
				.NbSectors   = 1,
		};

		uint32_t PageError;

		// erase page
		result = HAL_FLASHEx_Erase(&EraseDefinitions, &PageError); // TODO: HAL_FLASHEx_Erase returns HAL_StatusTypeDef not the NVRAM_Result_e
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}
	}
	// else write status to flash
	else
	{
		result = HAL_FLASH_Program(FLASH_TYPEPROGRAM_HALFWORD, Page, PageStatus); // TODO: HAL_FLASH_Program returns HAL_StatusTypeDef not the NVRAM_Result_e
		if (result != NVRAM_SUCCESS)
		{
			return result;
		}
	}

	// update global page status variables (remove page from old status and attach to new status)
	if (NVRAM_ValidPage == Page)
	{
		NVRAM_ValidPage = NVRAM_PAGE_NONE;
	}
	else if (NVRAM_ReceivingPage == Page)
	{
		NVRAM_ReceivingPage = NVRAM_PAGE_NONE;
	}
	else if (NVRAM_ErasedPage == Page)
	{
		NVRAM_ErasedPage = NVRAM_PAGE_NONE;
	}

	if (PageStatus == NVRAM_VALID)
	{
		NVRAM_ValidPage = Page;
	}
	else if (PageStatus == NVRAM_RECEIVING)
	{
		NVRAM_ReceivingPage = Page;
	}
	else if (PageStatus == NVRAM_ERASED)
	{
		NVRAM_ErasedPage = Page;
	}

	return NVRAM_SUCCESS;
}


// reads the whole page, fills the index with variable addresses and the size table with variable sizes
// - declare variables
// - ignore call when Page is PAGE_NONE
// - get page addresses
// - loop through page addresses
// - read potential variable header
// - if no header written
//		- loop through next 4 halfword and check if there is anything written
//		- while looping count the size of written data
//		- if no data found, last variable of page was reached (return)
// - else (if header written)
//		- get size code
//		- check for valid name
//		- if everything valid, update the index and the size table
//		- calculate size in bytes from size code
// - go to next address on page
// - set next free flash address
// - return on loop end
//
// Page:	page to search for variables
// return:	NVRAM_SUCCESS
static NVRAM_Result_e NVRAM_PageToIndex(NVRAM_Page_e Page)
{
	// declare variables
	uint16_t VariableHeader;								// header of current variable (first 2 bits size code, rest name)
	uint8_t SizeCode;										// size of current variable as Size code
	uint8_t Size;											// size of current variable in bytes
	uint16_t Name;											// name of current variable

	// ignore call when Page is PAGE_NONE
	if (Page == NVRAM_PAGE_NONE)
	{
		return NVRAM_SUCCESS;
	}

	// get page addresses
	uint32_t Address = Page + 2;
	uint32_t PageEndAddress = Page + FLASH_PAGE_SIZE;

	//loop through page starting after page header
	while (Address < PageEndAddress)
	{
		// read potential variable header
		VariableHeader = *((__IO uint16_t*) Address);

		// if no header written (causes: end of data reached or reset while writing)
		if (VariableHeader == 0xFFFF)
		{
			// loop through next 4 halfword and check if there is anything written
			Size = 0;
			for (uint8_t i = 2; i <= 8; i += 2)
			{
				if (Address + i >= PageEndAddress)
				{
					break;
				}
				// while looping count the size of written data (resulting from reset while writing)
				if (*((__IO uint16_t*) (Address + i)) != 0xFFFF)
				{
					Size = i;
				}
			}
			// if no data found, last variable of page was reached (end loop)
			if (Size == 0)
			{
				break;
			}
		}
		// else (if header written, proper variable value is following)
		else
		{
			// get size code
			SizeCode = VariableHeader >> 14;

			// check for valid name (VARIABLE_COUNT might have been reduced between builds, but old variables are still in flash)
			Name = VariableHeader & 0b0011111111111111;
			if (Name < NVRAM_VARIABLE_COUNT)
			{
				// if everything valid, update the index and the size table
				NVRAM_Index[Name] = Address + 2 - NVRAM_START_ADDRESS;
				NVRAM_SizeTable[Name] = SizeCode;
				if (SizeCode == NVRAM_SIZE_DELETED)
				{
					NVRAM_Index[Name] = 0;
				}
			}

			// calculate size in bytes from size code
			Size = 1 << SizeCode;
			if (SizeCode == NVRAM_SIZE_DELETED)
			{
				Size = 0;
			}
		}

		// go to next address on page
		Address = Address + 2 + Size;
	}

	// set next free flash address
	NVRAM_NextIndex = Address;
	if (Address >= PageEndAddress)
	{
		NVRAM_NextIndex = 0;
	}

	// return on loop end
	return NVRAM_SUCCESS;
}
